### PR TITLE
Upgrade to Cowboy 2

### PR DESCRIPTION
**Pull request by efcasado**
This pull-request is about upgrading Maru to use the latest major version of Cowboy (i.e. 2.X).

https://ninenines.eu/articles/cowboy-2.0.0/

The Plug upgrade is just a byproduct of upgrading Cowboy. The Cowboy2 adapter is new in Plug 1.5.

### CODE REVIEW

**Comment by efcasado** [comment]
Looks like Cowboy 2 does not like Erlang/OTP 18.

**Comment by falood** [comment]
Hi @efcasado 
I did https://github.com/elixir-maru/maru/commit/092b46a4852a0ed068bc95d8af797d6755ba4a81 just now, I think we don't need to change the code, plug v1.5 will works for cowboy 1.x and 2.x.
Thank you 🙂

**Comment by efcasado** [comment]
Cool!

No, you won't need to change code. What I meant is that Cowboy 2.X does not compile using Erlang/OTP18. Not a big deal, though.

Looking forward to using this latest version of Maru.

**Comment by falood** [comment]
I have remove otp 18 support from travis script, let's deprecate otp18 🙂
will bump a version asap

**Pull request closed without merging**
